// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

export default {
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "prisma/seed.ts",
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
};
